# Generated by Django 5.1.3 on 2024-12-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='orders.tabledetails'),
            preserve_default=False,
        ),
    ]
