# Generated by Django 5.1.3 on 2024-12-21 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_table_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='table_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.tabledetails'),
        ),
        migrations.AlterField(
            model_name='tabledetails',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tabledetails',
            name='table_number',
            field=models.IntegerField(unique=True),
        ),
    ]
