# Generated by Django 5.1.3 on 2024-12-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_table_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='table_details',
        ),
        migrations.AlterField(
            model_name='tabledetails',
            name='customer_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tabledetails',
            name='table_number',
            field=models.IntegerField(),
        ),
    ]
