# Generated by Django 5.1.3 on 2025-01-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='Name', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.IntegerField(default=1),
        ),
    ]
